### ISSUE TITLE
Add Travis config

### ISSUE THREAD

**Issue by mre** [mre/tinysearch#3]
Would be great to build the project on every new commit / pull request.
For that, we could add a Travis configuration.

**Comment by schalkneethling** [comment]
@mre Hey there, I would like to take this one. I am guessing that you want to run the default Rust build script on PR/commit i.e. `cargo build`

Is there a specific version of Rust you want to target? Perhaps simply `release`?
Do you also want to run `cargo test`?

**Comment by mre** [comment]
Hey @schalkneethling,
yeah I think a setup like this would be a good start: https://github.com/mre/mos6502/pull/4/files
This runs `cargo build` and `cargo test`. You might also want to add a badge to the `README.md` if you can. Once we got this up and running, we might wanna think about adding support for wasm-pack to Travis, as described in #2.

**Comment by schalkneethling** [comment]
Sounds good @mre - on it.

**Comment by mre** [comment]
Fixed by @schalkneethling in #6. 🎉
