### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kanishkarj** [mre/tinysearch#90]
Hey @mre ! 

An interesting project! I'm working on a related effort in a CNCF special interest group and would love to exchange notes. The Layer5 open source community has a growing focus on WASM / Rust. I welcome you to join - http://slack.layer5.io. You might find use in some of the ongoing initiatives in the community. Ping me when you do - @kanishkarj !

**Comment by mre** [comment]
Cool. Just sent you message over on Slack. Guess we can close this for now and maybe reopen in the future if we want to document anything from the Slack conversation. Thanks for getting in touch!
